test/v8tests/call.js:32:1: [definite] ReferenceError, reading absent variable assertTrue
test/v8tests/call.js:28:1: [definite] Unreachable function f0
test/v8tests/call.js:32:12: [definite] Unreachable code
test/v8tests/call.js:46:5: [definite] The variable x is never used
test/v8tests/call.js:52:1: [definite] Unreachable function f1
test/v8tests/call.js:63:1: [definite] Unreachable function f2
test/v8tests/call.js:77:1: [definite] Unreachable function fn
test/v8tests/call.js:1:1: [maybe] Uncaught exception, constructed at [test/v8tests/call.js:32:1]
